### ISSUE TITLE
how to adapt for slightly different protocol

### ISSUE THREAD

**Issue by drahdiwaberl** [lNikazzzl/tcl_ac_esphome#4]
well, cheered to early.

just discovered that for my Vesker branded A/C i can't set the swing modes from esphome. but they are read correctly if i do set them with the IR-remote.

@lNikazzzl could you help me to find the parts of tcl_climate.h i'd need to adapt if i wanted to implement the bytes of the protocol documented here: https://github.com/adaasch/AC-hack .. is it line 320 to 371?

@SidColt do the swing-mode commands work for your Kesser device?

**Comment by SidColt** [comment]
I am using esphome inside home assistant.
Climate control template I only visualization of swing mode because I guess the template does not support detailed swing.

But you can add as extra Entity. There you have full control.

What you can try is, enable esp web server on your device. There swing mode is also supported.

**Comment by lNikazzzl** [comment]
> well, cheered to early.
> 
> just discovered that for my Vesker branded A/C i can't set the swing modes from esphome. but they are read correctly if i do set them with the IR-remote.
> 
> @lNikazzzl could you help me to find the parts of tcl_climate.h i'd need to adapt if i wanted to implement the bytes of the protocol documented here: https://github.com/adaasch/AC-hack .. is it line 320 to 371?
> 
> @SidColt do the swing-mode commands work for your Kesser device?

Are you using these extra settings in the red circle? Or are you trying to change it through the climate device? [
![IMG_9739](https://github.com/user-attachments/assets/ac918d82-4ab8-4917-9656-b9c055f49b48)
](url)

**Comment by drahdiwaberl** [comment]
oh, right - didn't add that configuration panel to the dashboard and totally forgot about it .. 😳 thanks.
