### ISSUE TITLE
UART config issue

### ISSUE THREAD

**Issue by margitin** [lNikazzzl/tcl_ac_esphome#5]
There was a problem with UART part of the YAML file. After adding the proper values, all works fine:
Working example in yaml config:
uart:
  id: uart_bus
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600
  parity: EVEN

Successfully installed on StarLight 12000 BTU. All works fine.

**Comment by lNikazzzl** [comment]
Yes, some users did notice that the hardware uart gpio1 gpio3 did not work correctly on some boards. Specifically on my devboard these pins work as well
