### ISSUE TITLE
possible to disable confirmation beep?

### ISSUE THREAD

**Issue by admiralroflknife** [lNikazzzl/tcl_ac_esphome#6]
I see the beep in the .h file, so i imagine there might be a way?

thank you for making this, totally saved me. 

for anyone else whos down the same rabbit hole, i can confirm this libary works for the zokop and rovsun model mini-splits

**Comment by admiralroflknife** [comment]
I looked online and it’s actually a fault from tcl design. I’ll just be going in a pulling out the buzzer instead.

**Comment by lNikazzzl** [comment]
Beeper is disabled programmatically, but I need to add support for it

**Comment by admiralroflknife** [comment]
> Beeper is disabled programmatically, but I need to add support for it

you are correct, im not a programmer by trade so blindly work through this.

I just went ahead and changed m_set_cmd.data.beep = 1; to   m_set_cmd.data.beep = 0;  in the tcl_climate.h and now the beep is gone. thank you again.
